sudo: required
services:
  - docker

before_install:
  - docker build -t cartron/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cartron/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-244142604025"
  bucket_path: "docker-react"
  access_key_id:
    secure: "QVq/1jEbILDVX0X4d/uHRi5eyQ/V4zRrD9PDJoEJGMn/+qQrQ9kmwU7Z/EgxM0emRpWabJ4VWb03GfUijJywN0qV7ke4hkQPWvXAVx1tV7ZrncIi+jOBULRn0hNXpu73uP7Hp+l7GXkhiiW+e2kjHblpI00wsK5seaL3N63y5pUpfixMWsVc57lzvSei83WPPCDFT1/iQE9dMzYD/V+B+1oBA1pxfU//wMQsw9uZbwTE7QpxuLYne4XwLfBL2V6KxXorsvQsI23dv2AvppHHGQT9iTWHevFY714gG459lDBFd0Qq9wUjz8IJCtdHCiagCZPSf8ofIYoWKKFW+7XM39URlXD+Kwf4qrPEiAacAHr/jcj0onGl3hJhsMNaMaW7zBPoyXF2TmbMPPn/zxNt/CbwcwWacpPpZGgXJ5B1IoopPj6B7Ps8PptDc54h2UCuVWN+Fq6r/j2+Hd1XvHNCVFZgURjW5CJWZsdByEMDNBoQ2RYOf+rF22LN7rbjKbzlgU6Dd+PFOu+ccQIT5MsF+7axnmUf1riDUDPcYqHwK2dxKpHu0owHfpeV/hdhDbLIJZ4BIElm728ktEcZff5hpkbmT6a9SRRJ+zht3CaKYFbRivzRrqNjRV+exX/xVDbWIdQGlxrrghuDRD52L2/bF37IOH5Wdlv93JCBNKijw4c="
  secret_access_key:
    secure: "l3zon9oYqEOZ5B3mCNlywNVo5YkMCu7y3eCw6QOrvEMC99SGylwDtTj8YXYa9B4BFUoXu6NrIxOPEVMUd/Q9eMy9YvRopMz5fFmaNsDCcppEEeNRjRmvG9LBPCyXSnnLLUqBsm+sGYBOjreZVvZzSANg5ao/dVBCQVAfY45ExjEXe6fzKvBCEt4vEkDKt+OCCSvQBBpmKUy7OAAUilTYJTSJlhfUtAYv0lv8jnf7fCjUIi1gfm55ASh08yZ04md8pPfyNpV4QYh3ehaUFwaCxtUSdy6dfrlZeX8NNFo9xi249zuanYbxP3Jp+TThM3csk+1ZYEp34wzMCceRvlRDX3TsydL7Y3cT95zoZyJ3kJW21XJXmiIrmOrQJxrG8cmhChn8N3Wy3D/SpZhDadZJQMq5bMOvzULRX+g3bZe99mg4G2RL4ekGuhJFB2Ie+6ynbyzwleQTTHx7ruHglkECp+beZiR/7+Tvk09LZsAjFiT8u+pznP8wufu58l70Vff7BVIls09gz9JFk4J0SzNT4aHmtzBTPnSO6e+AoWK8vWRVLwNGI8wg5RSA1kznpo3aPCSXXnUI5oqcuXc1himOU1cNpsJzjQ0jgGTJhiuru/KRQwL4Iv8Jfg/t8R/FhVYyTg/i2TGU2dLc9ewFRgDTLUv8pFbIwmjdm5GzVeba4Ew="
  on:
    branch: master
